// Code generated by protoc-gen-go. DO NOT EDIT.
// source: docker/service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContainerStats_MemorySize int32

const (
	ContainerStats_B  ContainerStats_MemorySize = 0
	ContainerStats_KB ContainerStats_MemorySize = 1
	ContainerStats_MB ContainerStats_MemorySize = 2
	ContainerStats_GB ContainerStats_MemorySize = 3
	ContainerStats_TB ContainerStats_MemorySize = 4
	ContainerStats_PB ContainerStats_MemorySize = 5
	ContainerStats_EB ContainerStats_MemorySize = 6
	ContainerStats_ZB ContainerStats_MemorySize = 7
	ContainerStats_YB ContainerStats_MemorySize = 8
)

var ContainerStats_MemorySize_name = map[int32]string{
	0: "B",
	1: "KB",
	2: "MB",
	3: "GB",
	4: "TB",
	5: "PB",
	6: "EB",
	7: "ZB",
	8: "YB",
}

var ContainerStats_MemorySize_value = map[string]int32{
	"B":  0,
	"KB": 1,
	"MB": 2,
	"GB": 3,
	"TB": 4,
	"PB": 5,
	"EB": 6,
	"ZB": 7,
	"YB": 8,
}

func (x ContainerStats_MemorySize) String() string {
	return proto.EnumName(ContainerStats_MemorySize_name, int32(x))
}

func (ContainerStats_MemorySize) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a226dac35484be2d, []int{4, 0}
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Created              int64    `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	Running              bool     `protobuf:"varint,6,opt,name=running,proto3" json:"running,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_a226dac35484be2d, []int{0}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Container) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Container) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Container) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

type GetAllContainersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllContainersRequest) Reset()         { *m = GetAllContainersRequest{} }
func (m *GetAllContainersRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllContainersRequest) ProtoMessage()    {}
func (*GetAllContainersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a226dac35484be2d, []int{1}
}

func (m *GetAllContainersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllContainersRequest.Unmarshal(m, b)
}
func (m *GetAllContainersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllContainersRequest.Marshal(b, m, deterministic)
}
func (m *GetAllContainersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllContainersRequest.Merge(m, src)
}
func (m *GetAllContainersRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllContainersRequest.Size(m)
}
func (m *GetAllContainersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllContainersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllContainersRequest proto.InternalMessageInfo

type ContainerCatalog struct {
	Containers           []*Container `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ContainerCatalog) Reset()         { *m = ContainerCatalog{} }
func (m *ContainerCatalog) String() string { return proto.CompactTextString(m) }
func (*ContainerCatalog) ProtoMessage()    {}
func (*ContainerCatalog) Descriptor() ([]byte, []int) {
	return fileDescriptor_a226dac35484be2d, []int{2}
}

func (m *ContainerCatalog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerCatalog.Unmarshal(m, b)
}
func (m *ContainerCatalog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerCatalog.Marshal(b, m, deterministic)
}
func (m *ContainerCatalog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerCatalog.Merge(m, src)
}
func (m *ContainerCatalog) XXX_Size() int {
	return xxx_messageInfo_ContainerCatalog.Size(m)
}
func (m *ContainerCatalog) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerCatalog.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerCatalog proto.InternalMessageInfo

func (m *ContainerCatalog) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ContainerStatsRequest struct {
	Container            string   `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerStatsRequest) Reset()         { *m = ContainerStatsRequest{} }
func (m *ContainerStatsRequest) String() string { return proto.CompactTextString(m) }
func (*ContainerStatsRequest) ProtoMessage()    {}
func (*ContainerStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a226dac35484be2d, []int{3}
}

func (m *ContainerStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerStatsRequest.Unmarshal(m, b)
}
func (m *ContainerStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerStatsRequest.Marshal(b, m, deterministic)
}
func (m *ContainerStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerStatsRequest.Merge(m, src)
}
func (m *ContainerStatsRequest) XXX_Size() int {
	return xxx_messageInfo_ContainerStatsRequest.Size(m)
}
func (m *ContainerStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerStatsRequest proto.InternalMessageInfo

func (m *ContainerStatsRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

type ContainerStats struct {
	Container            string                    `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	CpuPercentage        float64                   `protobuf:"fixed64,2,opt,name=cpu_percentage,json=cpuPercentage,proto3" json:"cpu_percentage,omitempty"`
	MemoryPercentage     float64                   `protobuf:"fixed64,3,opt,name=memory_percentage,json=memoryPercentage,proto3" json:"memory_percentage,omitempty"`
	MemoryLimit          float64                   `protobuf:"fixed64,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	MemorySizeType       ContainerStats_MemorySize `protobuf:"varint,5,opt,name=memory_size_type,json=memorySizeType,proto3,enum=dockerservice.ContainerStats_MemorySize" json:"memory_size_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ContainerStats) Reset()         { *m = ContainerStats{} }
func (m *ContainerStats) String() string { return proto.CompactTextString(m) }
func (*ContainerStats) ProtoMessage()    {}
func (*ContainerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_a226dac35484be2d, []int{4}
}

func (m *ContainerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerStats.Unmarshal(m, b)
}
func (m *ContainerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerStats.Marshal(b, m, deterministic)
}
func (m *ContainerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerStats.Merge(m, src)
}
func (m *ContainerStats) XXX_Size() int {
	return xxx_messageInfo_ContainerStats.Size(m)
}
func (m *ContainerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerStats.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerStats proto.InternalMessageInfo

func (m *ContainerStats) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *ContainerStats) GetCpuPercentage() float64 {
	if m != nil {
		return m.CpuPercentage
	}
	return 0
}

func (m *ContainerStats) GetMemoryPercentage() float64 {
	if m != nil {
		return m.MemoryPercentage
	}
	return 0
}

func (m *ContainerStats) GetMemoryLimit() float64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

func (m *ContainerStats) GetMemorySizeType() ContainerStats_MemorySize {
	if m != nil {
		return m.MemorySizeType
	}
	return ContainerStats_B
}

func init() {
	proto.RegisterEnum("dockerservice.ContainerStats_MemorySize", ContainerStats_MemorySize_name, ContainerStats_MemorySize_value)
	proto.RegisterType((*Container)(nil), "dockerservice.Container")
	proto.RegisterType((*GetAllContainersRequest)(nil), "dockerservice.GetAllContainersRequest")
	proto.RegisterType((*ContainerCatalog)(nil), "dockerservice.ContainerCatalog")
	proto.RegisterType((*ContainerStatsRequest)(nil), "dockerservice.ContainerStatsRequest")
	proto.RegisterType((*ContainerStats)(nil), "dockerservice.ContainerStats")
}

func init() { proto.RegisterFile("docker/service.proto", fileDescriptor_a226dac35484be2d) }

var fileDescriptor_a226dac35484be2d = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xee, 0x26, 0x6d, 0xee, 0x3a, 0x67, 0xc3, 0xde, 0x72, 0xea, 0x2a, 0x8a, 0x35, 0xa8, 0x04,
	0x84, 0x2a, 0x15, 0xc1, 0x57, 0xf7, 0x94, 0x3e, 0x78, 0x07, 0xc7, 0xf6, 0x5e, 0x3c, 0x94, 0x12,
	0xd3, 0xa1, 0x2c, 0x36, 0x3f, 0x4c, 0x36, 0x42, 0xef, 0xbf, 0xf0, 0xff, 0x12, 0xff, 0x26, 0xd9,
	0x4d, 0x9a, 0x6b, 0x0b, 0xed, 0xd3, 0xb7, 0xf3, 0xcd, 0x37, 0xc9, 0xcc, 0xb7, 0xb3, 0x70, 0x36,
	0xcf, 0xe2, 0x9f, 0x58, 0xbc, 0x29, 0xb1, 0xf8, 0xad, 0x62, 0x1c, 0xe5, 0x45, 0xa6, 0x33, 0x36,
	0xa8, 0xd9, 0x86, 0x0c, 0xfe, 0x10, 0xe8, 0x9f, 0x67, 0xa9, 0x8e, 0x54, 0x8a, 0x05, 0xf3, 0xc1,
	0x51, 0x73, 0x4e, 0x86, 0x24, 0xec, 0x4b, 0x47, 0xcd, 0x19, 0x83, 0x6e, 0x1a, 0x25, 0xc8, 0x1d,
	0xcb, 0xd8, 0x33, 0x7b, 0x00, 0x5e, 0xa9, 0x23, 0x5d, 0x95, 0xdc, 0xb5, 0x6c, 0x13, 0xb1, 0x33,
	0xe8, 0x99, 0x13, 0xf2, 0xae, 0xa5, 0xeb, 0x80, 0x71, 0x38, 0x8a, 0x0b, 0x8c, 0x34, 0xce, 0x79,
	0x6f, 0x48, 0x42, 0x57, 0xae, 0x43, 0x93, 0x29, 0xaa, 0x34, 0x55, 0xe9, 0x82, 0x7b, 0x43, 0x12,
	0x1e, 0xcb, 0x75, 0x18, 0x3c, 0x82, 0x87, 0x13, 0xd4, 0x1f, 0x97, 0xcb, 0xb6, 0xb1, 0x52, 0xe2,
	0xaf, 0x0a, 0x4b, 0x1d, 0x5c, 0x00, 0x6d, 0xc9, 0xf3, 0x48, 0x47, 0xcb, 0x6c, 0xc1, 0x3e, 0x00,
	0xc4, 0xad, 0x90, 0x93, 0xa1, 0x1b, 0x9e, 0x8c, 0xf9, 0x68, 0x6b, 0xcc, 0x51, 0x5b, 0x24, 0x37,
	0xb4, 0xc1, 0x7b, 0xb8, 0xdf, 0x26, 0xa6, 0x3a, 0xd2, 0xeb, 0xdf, 0xb0, 0x27, 0xd0, 0x6f, 0x65,
	0x8d, 0x1d, 0x77, 0x44, 0xf0, 0xcf, 0x01, 0x7f, 0xbb, 0xee, 0x70, 0x01, 0x7b, 0x09, 0x7e, 0x9c,
	0x57, 0xb3, 0x1c, 0x8b, 0x18, 0x53, 0x1d, 0x2d, 0x6a, 0x43, 0x89, 0x1c, 0xc4, 0x79, 0x75, 0xd5,
	0x92, 0xec, 0x35, 0x9c, 0x26, 0x98, 0x64, 0xc5, 0x6a, 0x53, 0xe9, 0x5a, 0x25, 0xad, 0x13, 0x1b,
	0xe2, 0xe7, 0x70, 0xaf, 0x11, 0x2f, 0x55, 0xa2, 0xb4, 0x75, 0x9d, 0xc8, 0x93, 0x9a, 0xbb, 0x30,
	0x14, 0x93, 0xd0, 0x94, 0xcd, 0x4a, 0x75, 0x8b, 0x33, 0xbd, 0xca, 0xd1, 0x5e, 0x82, 0x3f, 0x0e,
	0xf7, 0xd9, 0x63, 0xa7, 0x19, 0x5d, 0xda, 0xaa, 0xa9, 0xba, 0x45, 0xe9, 0x27, 0xed, 0xf9, 0x7a,
	0x95, 0x63, 0x30, 0x05, 0xb8, 0xcb, 0xb2, 0x1e, 0x10, 0x41, 0x3b, 0xcc, 0x03, 0xe7, 0x8b, 0xa0,
	0xc4, 0xe0, 0xa5, 0xa0, 0x8e, 0xc1, 0x89, 0xa0, 0xae, 0xc1, 0x6b, 0x41, 0xbb, 0x06, 0xaf, 0x04,
	0xed, 0x19, 0xfc, 0x2c, 0xa8, 0x67, 0xf0, 0x46, 0xd0, 0x23, 0x83, 0x5f, 0x05, 0x3d, 0x1e, 0xff,
	0x25, 0x30, 0xf8, 0x64, 0x1b, 0x9a, 0xd6, 0x0d, 0xb1, 0xef, 0x40, 0x77, 0x57, 0x80, 0xbd, 0xda,
	0x69, 0x7a, 0xcf, 0x8e, 0x3c, 0x7e, 0xb6, 0x6f, 0xb8, 0x66, 0x61, 0x82, 0x0e, 0xfb, 0x06, 0xa7,
	0x13, 0xd4, 0x3b, 0x77, 0xf8, 0xe2, 0xa0, 0x29, 0xeb, 0xaf, 0x3f, 0x3d, 0xa8, 0x0a, 0x3a, 0x6f,
	0x89, 0xa0, 0x37, 0xfe, 0xf6, 0xd3, 0xfb, 0xe1, 0xd9, 0xb7, 0xf7, 0xee, 0x7f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x81, 0xfe, 0x3c, 0x0f, 0x93, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DockerServiceClient is the client API for DockerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DockerServiceClient interface {
	GetAllContainers(ctx context.Context, in *GetAllContainersRequest, opts ...grpc.CallOption) (*ContainerCatalog, error)
	GetContainerStats(ctx context.Context, in *ContainerStatsRequest, opts ...grpc.CallOption) (DockerService_GetContainerStatsClient, error)
}

type dockerServiceClient struct {
	cc *grpc.ClientConn
}

func NewDockerServiceClient(cc *grpc.ClientConn) DockerServiceClient {
	return &dockerServiceClient{cc}
}

func (c *dockerServiceClient) GetAllContainers(ctx context.Context, in *GetAllContainersRequest, opts ...grpc.CallOption) (*ContainerCatalog, error) {
	out := new(ContainerCatalog)
	err := c.cc.Invoke(ctx, "/dockerservice.DockerService/GetAllContainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) GetContainerStats(ctx context.Context, in *ContainerStatsRequest, opts ...grpc.CallOption) (DockerService_GetContainerStatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DockerService_serviceDesc.Streams[0], "/dockerservice.DockerService/GetContainerStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &dockerServiceGetContainerStatsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DockerService_GetContainerStatsClient interface {
	Recv() (*ContainerStats, error)
	grpc.ClientStream
}

type dockerServiceGetContainerStatsClient struct {
	grpc.ClientStream
}

func (x *dockerServiceGetContainerStatsClient) Recv() (*ContainerStats, error) {
	m := new(ContainerStats)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DockerServiceServer is the server API for DockerService service.
type DockerServiceServer interface {
	GetAllContainers(context.Context, *GetAllContainersRequest) (*ContainerCatalog, error)
	GetContainerStats(*ContainerStatsRequest, DockerService_GetContainerStatsServer) error
}

func RegisterDockerServiceServer(s *grpc.Server, srv DockerServiceServer) {
	s.RegisterService(&_DockerService_serviceDesc, srv)
}

func _DockerService_GetAllContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).GetAllContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dockerservice.DockerService/GetAllContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).GetAllContainers(ctx, req.(*GetAllContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_GetContainerStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContainerStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DockerServiceServer).GetContainerStats(m, &dockerServiceGetContainerStatsServer{stream})
}

type DockerService_GetContainerStatsServer interface {
	Send(*ContainerStats) error
	grpc.ServerStream
}

type dockerServiceGetContainerStatsServer struct {
	grpc.ServerStream
}

func (x *dockerServiceGetContainerStatsServer) Send(m *ContainerStats) error {
	return x.ServerStream.SendMsg(m)
}

var _DockerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dockerservice.DockerService",
	HandlerType: (*DockerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllContainers",
			Handler:    _DockerService_GetAllContainers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetContainerStats",
			Handler:       _DockerService_GetContainerStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "docker/service.proto",
}
